version: "3.9"
services:
  postgres:
    container_name: ${APP_NAME}_database_container
    image: postgres:15-alpine
    env_file: .env
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - data_volume:/var/lib/postgresql/data
  # redis:
  #   image: redis:7-alpine
  pgadmin:
    container_name: ${APP_NAME}_pgadmin_container
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    # networks:
    #   - ${APP_NAME}-network
    restart: unless-stopped

volumes:
  data_volume:
  pgadmin:

networks:
  ${APP_NAME}-network:
