#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	    CREATE ROLE greenlight WITH PASSWORD 'pa55word' LOGIN;
	    GRANT USAGE ON SCHEMA public TO greenlight;
	    GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO greenlight;
	    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO greenlight;
	    GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO greenlight;
	    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO greenlight;
	    ALTER ROLE greenlight SET search_path = public;
EOSQL
